dmfs/opentasks

res/values-fr/strings.xml

Hello,
I improved the French translation. I made some changes and added missing strings.
Greetings

Update French translation

---

opentasks/src/main/AndroidManifest.xml
opentasks/src/main/res/values-de/strings.xml
opentasks/src/main/res/values-es/strings.xml
opentasks/src/main/res/values-fr/strings.xml
opentasks/src/main/res/values-it/strings.xml
opentasks/src/main/res/values-nl/strings.xml
opentasks/src/main/res/values-pl/strings.xml
opentasks/src/main/res/values-pt-rPT/strings.xml
opentasks/src/main/res/values-pt-rbr/strings.xml
opentasks/src/main/res/values-ru/strings.xml
opentasks/src/main/res/values-sr/strings.xml
opentasks/src/main/res/values-uk/strings.xml
opentasks/src/main/res/values/strings.xml

activity_add_task_title ("Create") left this clarification up to the icon

clarify intent label ("Add task")

---

build.gradle

Update android gradle plugin to 2.2.0

---

opentasks/src/main/res/layout-v11/text_field_editor.xml
opentasks/src/main/res/layout/checklist_field_editor_element.xml
opentasks/src/main/res/layout/fragment_input_text_dialog.xml
opentasks/src/main/res/layout/fragment_quick_add_dialog.xml

PR - Set all EditTexts to use textCapSentences inputType

---

opentasks/src/main/java/org/dmfs/tasks/notification/NotificationUpdaterService.java

Fix updating pinned notification upon completion.

---

opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java

Note: the whole method appears as change in the diff because of whitespace changes.
(I am not sure at the moment how to handle the code styles in this project..)

Open task after saved with editor. #254

---

opentasks/src/main/res/values-sk/strings.xml

I was not able to find a language switcher, so I didn't add Slovak option there. But localization file is complete. Translation is based on Czech localization file.

Added Slovak localization file

---

opentasks/src/main/res/values-nl/strings.xml

I can't of course check the translation correctness but the diff looked good. 
Just replaced "..." sequences with ellipsis character as Android suggested.

Update Dutch translations with file from Toon. #390

---

opentasks/src/main/res/values-v11/styles.xml
opentasks/src/main/res/values/styles.xml

When trying to create widget:
10-28 15:12:24.529 26747 26747 E AndroidRuntime: FATAL EXCEPTION: main
10-28 15:12:24.529 26747 26747 E AndroidRuntime: Process: org.dmfs.tasks, PID: 26747
10-28 15:12:24.529 26747 26747 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.dmfs.tasks/org.dmfs.tasks.homescreen.TaskListWidgetSettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
10-28 15:12:24.529 26747 26747 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
10-28 15:12:24.529 26747 26747 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
10-28 15:12:24.529 26747 26747 E AndroidRuntime: 	at …

Theme.MaterialDialog needs to be AppCompat

---

opentasks/src/main/java/org/dmfs/tasks/utils/BaseActivity.java
opentasks/src/main/java/org/dmfs/tasks/utils/ManifestAppName.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/AppPermissions.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/BasicAppPermissions.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/LegacyAppPermissions.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/MarshmallowPermissions.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/NoOpPermissionRequest.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/Permission.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/PermissionRequest.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/dialog/PermissionRequestDialogFragment.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/utils/AppSettingsIntent.java
opentasks/src/main/java/org/dmfs/tasks/utils/permission/utils/ManifestPermissionStrings.java
opentasks/src/main/res/layout/dialog_message.xml
opentasks/src/main/res/values/strings.xml

@dmfs I am submitting this now so you can check and decide on UX steps and the exact messages, but the code is not finalized here. I will get back to this when the permission handling library is ready. (Or let me know if it's better to not wait for that.)

Requesting GET_ACCOUNTS permission on startup. #407

---

opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskDatabaseHelper.java
opentasks/src/main/AndroidManifest.xml
opentasks/src/main/java/org/dmfs/tasks/notification/TaskNotificationHandler.java
opentasks/src/main/res/layout/activity_manage_task_list.xml
opentasks/src/main/res/layout/checklist_field_view.xml
opentasks/src/main/res/layout/fragment_quick_add_dialog_header.xml
opentasks/src/main/res/layout/opentasks_location_field_view.xml
opentasks/src/main/res/layout/task_editor_activity.xml
opentasks/src/main/res/layout/task_list_group.xml
opentasks/src/main/res/layout/task_list_group_single_line.xml
opentasks/src/main/res/layout/visible_task_list_item.xml
opentasks/src/main/res/menu/task_list_activity_menu.xml

Automated code inspection by android studio. Fixing problems AS can fix automatically

automated code inspect

---

opentasks/src/main/res/values-nl/strings.xml

Updated version of #679 with different translation of "task_classification".

Updated Dutch translation by Toon van Gerwen

---

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
opentasks-contract/build.gradle
opentasks-provider/build.gradle
opentasks/build.gradle
opentaskspal/build.gradle

This adds a plugin which allows for publishing the app autimatically to Google Play.

Add plugin to publish app, #718

---

opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java
opentasks/src/main/java/org/dmfs/tasks/model/ContentSet.java

It's no longer necessary to update all values which affect recurrince in the same update. The provider can handle updates of individual fields.

Remove obsolte code, implements #834

---

opentasks-provider/src/main/res/values-it/strings.xml
opentasks/src/main/res/values-it/strings.xml

Hi, I noticed that Italian translation was a bit outdated. I updated it with new strings took from English translation.
There should not be any error in the XML files, anyway if there are some errors do not hesitate to notify me!

Update italian translation

---

opentasks/src/main/res/values-pl/strings.xml

Update information translation.

One more PL update

---

opentasks-theme/src/main/res/values/theme_light.xml
opentasks/src/main/java/org/dmfs/tasks/groupings/BaseTaskViewDescriptor.java
opentasks/src/main/res/layout/fragment_expandable_task_list.xml
opentasks/src/main/res/layout/task_list_element.xml
opentasks/src/main/res/values/styles.xml

Improve the list layout by reducing margins and removing obsolete
elements and code.
It doesn't quite fix the scrollbar size on tablets for some reason. This
needs further investigation.

Simplify and improve list layout

---

dependencies.gradle
opentasks/build.gradle
opentasks/src/main/java/org/dmfs/tasks/linkify/ActionModeLinkify.java
opentasks/src/main/java/org/dmfs/tasks/linkify/ViewObservables.java
opentasks/src/main/java/org/dmfs/tasks/widget/DescriptionFieldView.java
opentasks/src/main/res/values-de/strings.xml
opentasks/src/main/res/values/strings.xml

Linkification of task description was temporarily removed when the
checklist implementation was improved. This commit introduces a floating
action mode which prompts the user before opening a link. This also
fixes #895.

Linkify Task description, fixes #929

---

opentasks/src/main/java/org/dmfs/tasks/groupings/BaseTaskViewDescriptor.java
opentasks/src/main/res/layout/task_list_element.xml

The last refactoring broke the layout of larger cards and cards of
closed tasks. This restores the correct look.

Fix layout in List view.

---

opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/CursorContentValuesInstanceAdapter.java
opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/CursorContentValuesListAdapter.java
opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/CursorContentValuesTaskAdapter.java
opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Instantiating.java

Reduce the number and size of database update operations by being a bit
smarter about when and what to update.

Task Provider performance improvements, fixes #979

---

opentasks/build.gradle
opentasks/src/main/java/org/dmfs/tasks/AppAppearanceSettingsFragment.java
opentasks/src/main/java/org/dmfs/tasks/AppNotificationSettingsFragment.java
opentasks/src/main/java/org/dmfs/tasks/AppSettingsActivity.java
opentasks/src/main/java/org/dmfs/tasks/TaskListActivity.java
opentasks/src/main/java/org/dmfs/tasks/groupings/BaseTaskViewDescriptor.java
opentasks/src/main/java/org/dmfs/tasks/groupings/ByDueDate.java
opentasks/src/main/java/org/dmfs/tasks/groupings/ByList.java
opentasks/src/main/java/org/dmfs/tasks/groupings/ByPriority.java
opentasks/src/main/java/org/dmfs/tasks/groupings/ByProgress.java
opentasks/src/main/java/org/dmfs/tasks/groupings/BySearch.java
opentasks/src/main/java/org/dmfs/tasks/groupings/ByStartDate.java
opentasks/src/main/res/values-de/strings.xml
opentasks/src/main/res/values/arrays.xml
opentasks/src/main/res/values/ints.xml
opentasks/src/main/res/values/prefs.xml
opentasks/src/main/res/values/strings.xml
opentasks/src/main/res/xml/app_preferences.xml
opentasks/src/main/res/xml/appearance_preferences.xml
opentasks/src/main/res/xml/notification_preferences.xml

Add a initial settings screen to tweak the list view items.

Settings for list view, implements #994

---

opentasks-theme/src/main/res/values-night-v23/theme_daynight.xml
opentasks-theme/src/main/res/values-night-v27/theme_daynight.xml
opentasks-theme/src/main/res/values-night/theme_daynight.xml
opentasks-theme/src/main/res/values-v23/theme_dark.xml
opentasks-theme/src/main/res/values-v23/theme_daynight.xml
opentasks-theme/src/main/res/values-v27/theme_dark.xml
opentasks-theme/src/main/res/values-v27/theme_daynight.xml
opentasks-theme/src/main/res/values-v27/theme_light.xml
opentasks-theme/src/main/res/values/attrs.xml
opentasks-theme/src/main/res/values/dimens.xml
opentasks-theme/src/main/res/values/theme.xml
opentasks-theme/src/main/res/values/theme_dark.xml
opentasks-theme/src/main/res/values/theme_daynight.xml
opentasks/src/main/AndroidManifest.xml
opentasks/src/main/java/org/dmfs/tasks/AppAppearanceSettingsFragment.java
opentasks/src/main/java/org/dmfs/tasks/AppSettingsActivity.java
opentasks/src/main/java/org/dmfs/tasks/TaskListActivity.java
opentasks/src/main/java/org/dmfs/tasks/groupings/BaseTaskViewDescriptor.java
opentasks/src/main/res/layout/activity_task_list.xml
opentasks/src/main/res/layout/fragment_quick_add_dialog.xml
opentasks/src/main/res/layout/opentasks_activity_preferences.xml
opentasks/src/main/res/layout/task_list_element.xml
opentasks/src/main/res/values-de/strings.xml
opentasks/src/main/res/values/bools.xml
opentasks/src/main/res/values/dimens.xml
opentasks/src/main/res/values/prefs.xml
opentasks/src/main/res/values/strings.xml
opentasks/src/main/res/values/styles.xml
opentasks/src/main/res/xml-v29/appearance_preferences.xml

This commit provides an initial dark theme for the list view.

Initial Dark Theme, implements #1003

---

opentasks-contract/src/main/java/org/dmfs/tasks/contract/TaskContract.java
opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskDatabaseHelper.java
opentasks/build.gradle
opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java
opentasks/src/main/java/org/dmfs/tasks/ViewTaskFragment.java
opentasks/src/main/java/org/dmfs/tasks/model/DefaultModel.java
opentasks/src/main/java/org/dmfs/tasks/model/Model.java
opentasks/src/main/java/org/dmfs/tasks/model/TaskFieldAdapters.java
opentasks/src/main/java/org/dmfs/tasks/model/XmlModel.java
opentasks/src/main/java/org/dmfs/tasks/model/adapters/DateTimeFieldAdapter.java
opentasks/src/main/java/org/dmfs/tasks/model/adapters/OptionalLongFieldAdapter.java
opentasks/src/main/java/org/dmfs/tasks/model/adapters/RRuleFieldAdapter.java
opentasks/src/main/java/org/dmfs/tasks/widget/RRuleFieldEditor.java
opentasks/src/main/java/org/dmfs/tasks/widget/recurrence/Conditional.java
opentasks/src/main/java/org/dmfs/tasks/widget/recurrence/NotRepeating.java
opentasks/src/main/java/org/dmfs/tasks/widget/recurrence/RecurrencePopupGenerator.java
opentasks/src/main/java/org/dmfs/tasks/widget/recurrence/RepeatByRule.java
opentasks/src/main/play/release-notes/en-GB/production.txt
opentasks/src/main/res/drawable/ic_baseline_repeat_24.xml
opentasks/src/main/res/layout/opentasks_rrule_field_editor.xml
opentasks/src/main/res/values/ids.xml
opentasks/src/main/res/values/strings.xml

Add a simple popup recurrence picker offering some common recurrence
patterns. Since there is no way to set an end to recurring tasks yet,
this commit also ensures they can at least be deleted.

Add simple recurrence picker. Implements #993

---

opentasks-theme/src/main/res/values/attrs.xml
opentasks-theme/src/main/res/values/colors.xml
opentasks-theme/src/main/res/values/theme_dark.xml
opentasks-theme/src/main/res/values/theme_light.xml
opentasks/src/main/java/org/dmfs/tasks/groupings/BaseTaskViewDescriptor.java
opentasks/src/main/res/drawable/task_progress_background_shade.xml
opentasks/src/main/res/layout/task_list_element.xml
opentasks/src/main/res/values-de/strings.xml
opentasks/src/main/res/values-fr/strings.xml
opentasks/src/main/res/values/arrays.xml
opentasks/src/main/res/values/bools.xml
opentasks/src/main/res/values/prefs.xml
opentasks/src/main/res/values/strings.xml
opentasks/src/main/res/values/styles.xml
opentasks/src/main/res/xml-v29/appearance_preferences.xml
opentasks/src/main/res/xml/appearance_preferences.xml

This also changes the progress preference from drop-down to switches.

Re-add progress gradient, implements #1009

---

opentasks/src/main/java/org/dmfs/tasks/linkify/ActionModeLinkify.java
opentasks/src/main/java/org/dmfs/tasks/utils/DescriptionMovementMethod.java
opentasks/src/main/java/org/dmfs/tasks/widget/DescriptionFieldView.java

Also fix a crash in case an action view is not shown and linkification
of the last link of a line.

Fix cursor movement, fixes #1024

---

opentasks/src/main/res/values-nl/strings.xml

Fix typo and improve some words

Improve Dutch translation

---

opentasks/src/main/res/values-pl/strings.xml
opentasks/src/main/res/values/strings.xml
opentasks/src/main/res/xml-v29/appearance_preferences.xml
opentasks/src/main/res/xml/appearance_preferences.xml

1. Correction and addition of the translation string for the Polish language.
2. Fixing the string for the title.
3. Change of function description for "Follow system" (#1030).

Fix string and correct PL translation 
