dmfs/opentasks

- opentasks/src/main/java/org/dmfs/tasks/model/DefaultModel.java
- opentasks/src/main/java/org/dmfs/tasks/model/XmlModel.java
- opentasks/src/main/java/org/dmfs/tasks/widget/LocationFieldView.java
- opentasks/src/main/res/layout/opentasks_location_field_view.xml
> PR for #149 location opens map (no.2)

- opentasks/src/main/java/org/dmfs/tasks/model/TaskFieldAdapters.java
- opentasks/src/main/java/org/dmfs/tasks/model/XmlModel.java
- opentasks/src/main/java/org/dmfs/tasks/model/adapters/FieldAdapter.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/AbstractConstraint.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/AdjustPercentComplete.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/ChecklistConstraint.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/NotAfter.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/NotBefore.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/ShiftIfAfter.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/ShiftTime.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/UpdateAllDay.java
Refactoring of `org.dmfs.tasks.model.contraints` and `FieldAdapter.addContraint(AbstractConstraint<Type> contraint)` in order to correct misspelling of "constraint" (fixes #307).
> fix spelling: contraint -> constraint

- opentasks/src/main/AndroidManifest.xml
- opentasks/src/main/java/org/dmfs/tasks/EditTaskActivity.java
- opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java
- opentasks/src/main/java/org/dmfs/tasks/QuickAddDialogFragment.java
- opentasks/src/main/java/org/dmfs/tasks/homescreen/TaskListWidgetProvider.java
- opentasks/src/main/java/org/dmfs/tasks/utils/RecentlyUsedLists.java
I'm using single widgets for every task list. In such a use case, it would be very useful, if a newly created task (using the `+` sign on the top-right corner of the widget) would use automatically the corresponding task list from the widget. Currently, the last selected list (from the previous edit) is used, which is often not desired.
This pull request therefore introduces a filter for the TaskList list in `EditTaskFragment`. Now, only such tasklists are shown, that are activated in the widget on which the `+` button was pressed.
What do you think about this solution? I see it as work in progress and looking forward for feedback.
> Improve task list selection when creating a new task from widget

- opentasks/src/main/java/org/dmfs/tasks/groupings/BySearch.java
- opentasks/src/main/java/org/dmfs/tasks/model/TaskFieldAdapters.java
- opentasks/src/main/java/org/dmfs/tasks/model/adapters/CustomizedDefaultFieldAdapter.java
- opentasks/src/main/java/org/dmfs/tasks/model/adapters/TimeFieldAdapter.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/After.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/BeforeOrShiftTime.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/NotAfter.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/NotBefore.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/ShiftIfAfter.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/ShiftTime.java
- opentasks/src/main/java/org/dmfs/tasks/model/constraints/UpdateAllDay.java
- opentasks/src/main/java/org/dmfs/tasks/model/defaults/Default.java
- opentasks/src/main/java/org/dmfs/tasks/model/defaults/DefaultAfter.java
- opentasks/src/main/java/org/dmfs/tasks/model/defaults/DefaultBefore.java
- opentasks/src/main/java/org/dmfs/tasks/widget/TimeFieldEditor.java
- opentasks/src/main/java/org/dmfs/tasks/widget/TimeFieldView.java
With the two new constraints, we prohibit `DUE=START` and therefore fix #262. The constraint `BeforeOrShiftTime` is a tradeoff between shifting always (cp. constraint `ShiftTime`) and shifting never (cp. constraint `NotAfter`); maybe this is sufficient in order to close #197.
> New constraints and defaults (forbid DUE=START)

- opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java
Note: I've reused an existing string for the toast message: "No task list available".
> Fix crash when saving task in editor with no list. #93

- opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java
> Fix having a duplicate view task screen after and edit. #379

- .idea/dictionaries/dictionary.xml
- opentasks/src/main/AndroidManifest.xml
- opentasks/src/main/java/org/dmfs/tasks/AppSettingsActivity.java
- opentasks/src/main/java/org/dmfs/tasks/AppSettingsFragment.java
- opentasks/src/main/java/org/dmfs/tasks/TaskListActivity.java
- opentasks/src/main/java/org/dmfs/tasks/notification/AlarmBroadcastReceiver.java
- opentasks/src/main/res/menu/task_list_activity_menu.xml
- opentasks/src/main/res/values/prefs.xml
- opentasks/src/main/res/xml/app_preferences.xml
The base branch is a new `settings/master` for this pull request, since I've only added the existing Notifications switch to the new Settings screen here, and I suppose we wouldn't release it with at least 2 items there.
One question here is the order of items in the menu. I see the items are added from both `TaskListActivity` and `TaskListFragment`. Since they are always shown together could we maybe use just one of them?
> Settings screen with Notifications checkbox. #279

- opentasks-provider/build.gradle
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderTest.java
- opentasks-provider/src/androidTest/res/values/opentasks_defaults.xml
- opentasks-provider/src/main/AndroidManifest.xml
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/AuthorityUtil.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskProvider.java
Remove dynamic authority resolution in AuthorityUtil.
---
Submitting this now for first check. There are many TODOs left in code.
A few specific notes:
- opentaskpal classes are not reviewed yet
- the contentpal test support ended up being one simple `Matcher` class basically, but I used this `Check` type to implement it and make an adapter for `Matcher`. I haven't thought it through yet since things got much more simple with the `Assert` operations. One thing is that `Matcher` seems not to be completely straighforward for me with the 3 base classes, also I think what we do here is more an execution which can throw Exception than a simple comparison of an already calculated value, so that's why this interface may be better.
We could also forget the hamcrest assert as well, I suppose, to …
> Tests for TaskProvider #410

- .travis.yml
- README.md
- opentasks/build.gradle
This also changes the version code to be based on commit count in the current branch rather than master. Apparently Travis doesn't fetch the master which caused this to fail.
Since we only publish master builds this should not have any unwanted side effects. Yet we spread the version code to allow inserting version numbers if necessary.
> Add .travis.yml. Implements #417

- build.gradle
As suggested, the `--always` flag is added to the `git describe --tags` command in the gradle file to avoid exiting when no tags found in the shallow clone on the CI.
> Fix CI build issue of not finding git tag. #486

- .idea/inspectionProfiles/Project_Default.xml
- opentasks/src/main/AndroidManifest.xml
This marks RTL as not supported in the manifest and also adds inspection configuration for Android Studio to ignore that warning, since as it seems it can't pick it up automatically from that manifest attribute.
> Mark RTL as not supported, disable IDE warning. #489

- opentasks/src/main/res/layout/fragment_synced_task_list.xml
Note that the text wrapping doesn't happen on Android 6.0, but I could reproduce it on 7.0 (may need to enter a longer text in place on 'cancel' to see it)
> Fix the wrapping of "CANCEL" on settings button on Android 7.x. #501

- opentasks-contract/src/main/java/org/dmfs/tasks/contract/TaskContract.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/handler/RelationHandler.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/ChildTaskRelationData.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/ParentTaskRelationData.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/RelationData.java
* remove all the `public static final` modifiers
* remove RELATED_URL
* remove some currently unsupported RelTypes
* convert RelTypes from enum to ints to allow unsupported reltypes.
> Revisit Relation contract. Implements #457

- opentasks-provider/src/main/java/org/dmfs/ngrams/NGramGenerator.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/FTSDatabaseHelper.java
Improve free text search by:
* Fixing n-gram generation when a space is added in front of a word
* give 4-grams a higher weight than multiple matches of the same 3-gram by not counting duplicate n-grams (as a result the score can not be >1 anymore)
* lower the min-score to 0.33 which means at least 1 out of 3 n-grams must match in order for a task to be considered a result
The changes are supposed to favor longer matches over many shorter matches.
> Fix & improve FTS. Implements #552

- opentasks/src/main/res/layout/list_spinner_item_selected.xml
Note, that I tried it with the inverse style as well:
```
@style/TextAppearance.AppCompat.Medium.Inverse
```
and that made white text on Android 7 but strangely it was black on Android 6. So I just set the color to white explicitly.
> Fix selected list font color on edit screen. #526

- opentasks-contract/src/main/java/org/dmfs/tasks/contract/TaskContract.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskDatabaseHelper.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Instantiating.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/instancedata/Stated.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/instancedata/VanillaInstanceData.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/InstanceValuesIterable.java
- opentasks-provider/src/test/java/org/dmfs/provider/tasks/processors/tasks/instancedata/VanillaInstanceDataTest.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/StatusData.java
This commit adds an instance status column which indicates which instance of a task is the next one to complete. This allows to filter out the instances which come after the next one.
> Add instance status column. Implements #572

- opentasks-contract/src/main/java/org/dmfs/tasks/contract/TaskContract.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskDatabaseHelper.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/instancedata/Distant.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/instancedata/VanillaInstanceData.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/InstanceValuesIterable.java
- opentasks-provider/src/test/java/org/dmfs/provider/tasks/processors/tasks/instancedata/DistantTest.java
- opentasks-provider/src/test/java/org/dmfs/provider/tasks/processors/tasks/instancedata/VanillaInstanceDataTest.java
This commit replaces the `instance_status` column with a more veratile `distance_from_current` which has additional semantics for upcoming instances.
> Replace `instance_status` by `distance_from_current`, implements #606

- .travis.yml
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskProvider.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/AbstractInstanceAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/ContentValuesInstanceAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/CursorContentValuesInstanceAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/InstanceAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/TaskAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/instances/TaskValueDelegate.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/instances/Validating.java
- opentaskspal/src/main/java/org/dmfs/opentaskstestpal/InstanceTestData.java
- opentaskspal/src/test/java/org/dmfs/opentaskstestpal/InstanceTestDataTest.java
This commit adds initial support for operations on the instances table. At present sync adapters are not allowed to write to the instances table, non-sync adapters can only insert or modify task values. Instances table columns are still read-only. This is meant to simplify working with recurrence in the UI. The UI won't have to take special care about creating exceptions. It can simply update or delete individual instances and the provider will take care of creating overrides or ex-dates.
> Introduce operations on Instances, implements #464

- opentasks/src/main/java/org/dmfs/tasks/QuickAddDialogFragment.java
- opentasks/src/main/java/org/dmfs/tasks/TaskListFragment.java
- opentasks/src/main/java/org/dmfs/tasks/ViewTaskFragment.java
- opentasks/src/main/java/org/dmfs/tasks/utils/SafeFragmentUiRunnable.java
This pull request adds a `Runnable` proxy/decorator class to be used in `Fragments` for safely posting a UI update.
Since this is general, I applied it at other places too (not just to fix the NPE in QuickAddDialogFragment),  where I found a `Runnable` in a `Fragment`.
It's called `SafeFragmentUiRunnable` but I also though about `AttachedAware`. But `SafeFragmentUiRunnable` just looks more descriptive at the places of usage. Especially the `Safe` part is reassuring ;)
> Fix NPE in QuickAddDialogFragment delayed UI update. #629

- opentasks/src/main/AndroidManifest.xml
- opentasks/src/main/java/org/dmfs/tasks/quicksettings/TaskQuickSettingsTile.java
- opentasks/src/main/res/values/strings.xml
This MR adds a simple QuickSettingsTile for OpenTasks, so you are able to create a task from your quick settings on the fly.
> Add QuickSettingsTile for easy task creation

- opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java
- opentasks/src/main/java/org/dmfs/tasks/TaskListActivity.java
Fix rotation issue after creating a task on a handset device.
> Always replace task details fragments instead of updating them. #624

- dependencies.gradle
- opentasks/src/main/java/org/dmfs/tasks/ManageListActivity.java
This commit switches from using the color picker as an activity via the open intent to using the color picker as a dialog fragment. This means the color picker is fixed now and no external picker can be used. It's not clear if anyone actually did that though.
> Use color picker dialog. Fixes #590

- opentasks/src/main/res/layout/activity_manage_task_list.xml
- opentasks/src/main/res/layout/checklist_field_view.xml
- opentasks/src/main/res/layout/fragment_quick_add_dialog_header.xml
- opentasks/src/main/res/layout/opentasks_location_field_view.xml
- opentasks/src/main/res/layout/task_list_group.xml
- opentasks/src/main/res/layout/task_list_group_single_line.xml
- opentasks/src/main/res/layout/visible_task_list_item.xml
Commit 5f4e901 contains a couple of changes which break the UI in that some elements don't respond to clicks anymore.
In particular the `focusable="true"` attirbute seems to cause these issues. For now We simply revert the addition of these attributes.
In another story we should address the issue and fix the layout.
> Partially restore 5f4e901, fixes #711

- opentasks/build.gradle
Adds an optional signing config, which is ignored if no keystore property is present.
> Add signing config, implements #720

- opentasks/src/main/java/org/dmfs/tasks/TaskListFragment.java
In an earlier commit we changed how the lists are loaded. Instead of loading them from the tasks table we now load them from the instances table. This was meant to prepare support for recurring tasks.
Unfortunately we missed on line where we were still using the `_id` column to get the task id (when we should actually use the `task_id` column now). This didn't cause any problem as long as the task id and the instance id where in sync (hence it wasn't an issue while testing). However, under certain circumstances this assumption is no longer true and caused an illegal Task URI to be loaded when clicking a task.
The list now uses the `task_id` column to create the task URI to show.
> Fix wrong ID being used. Fixes #723

- build.gradle
- opentasks/build.gradle
Update the publish configuration to derive the publishing track form the version number.
> Auto-Determine release channel, implements #725

- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskProvider.java
- opentasks/build.gradle
- opentasks/src/main/AndroidManifest.xml
- opentasks/src/main/java/org/dmfs/tasks/StaleListBroadcastReceiver.java
- opentasks/src/main/java/org/dmfs/tasks/utils/BaseActivity.java
- opentaskspal/build.gradle
- opentaskspal/src/main/java/org/dmfs/opentaskspal/predicates/AnyOf.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/predicates/BinaryPredicate.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/views/TaskListsView.java
This commit adds a workaround for sync apps which don't grant account visibility to OpenTasks. If a task list is inserted which belongs to an account which we can't see, the app asks for permission to see the account.
The `GET_ACCOUNTS` permission is no longer used on Android 8+ and the request for that permission will no longer be shown when the app starts.
> Request account visibility, implements #728

- opentasks/build.gradle
The regular expression for the internal track didn't cover a revision descirption like `1.1.16-dirty` which is a release commit with changes.
The proposed fix makes the part between the version number and `-dirty` optional.
> Fix track selection, fixes #747

- dependencies.gradle
- opentasks-provider/src/main/java/org/dmfs/ngrams/NGramGenerator.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/FTSDatabaseHelper.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/Chunked.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/ChunkedIterator.java
- opentasks-provider/src/test/java/org/dmfs/provider/tasks/utils/ChunkedTest.java
The previous implementation tried to use the CONFLICT_IGNORE policy when inserting new ngrams and was falling back to a query in case it failed to find the id of the exiting ngram. This was very slow because it meant an expensive query for every ngram to insert.
The new solution goes over the existing ngrams and only inserts the ones which don't exist in the database. Similarily the ngram relations table is not cleared for the particular task, instead the existing ngrams are loaded and only new relations are inserted and obsolete relations are removed.
> Improve FTS performance, fixes #750

- opentasks-provider/src/main/java/org/dmfs/provider/tasks/SQLiteContentProvider.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Searchable.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/Profiled.java
In order to evaluate the provider performance and its impact on the UX this commit adds some simple profiling statments which measure the execution time of certain operations and write them to logcat.
Hopefully this helps a but to detect slow operations and bottlenecks.
> Add some simple profiling for provider operations. supports #738

- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskProvider.java
Reduces/removes lag while background sync (#738)
Also avoids reloading widget multiple times after a change to a task.
> ignore updates to sync adapter only columns

- opentasks-contract/src/main/java/org/dmfs/tasks/contract/TaskContract.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskDatabaseHelper.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/TaskAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Validating.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/VersionData.java
This commit adds a read-only task VERSION column which is incremented upon any update or a task (including sync-adapter updates).
The column serves two purposes:
* safe transactions by asserting a specific version before updating a task
* quick detection if a specific task has been modified
The former could be used by sync-adapters to ensure a task has not been updated while being synced.
Notifications will make use of the latter to avoid unnecessary updates of task notifications for unchanged tasks.
> Add VERSION column, implements #778

- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskDatabaseHelper.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/TableColumns.java
The cause of issue #793 is actually unknown but this once could be a good candidate. In few cases the database might already be on version 20 but the version column had not been created.
This might be caused by having the beta version installed before (which already had a version 20, but without the column).
This fix always checks if the version column already exists and creates it otherwise.
> Create version column if required, fixes #793

- opentasks/src/main/java/org/dmfs/tasks/actions/NotifyAction.java
- opentasks/src/main/java/org/dmfs/tasks/notification/ActionService.java
This sets a "notification cancelled" intent which removes the persisted entry when the notification is swiped away.
> Fix permanent notification, fixes #800

- dependencies.gradle
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskProvider.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/Utils.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/ResourceArray.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/With.java
- opentasks-provider/src/main/res/values/opentasks_provider_changed_receivers.xml
Since Android 8 it's not possible to listen to implicit broadcasts anymore when the receiver is declared in the AndroidManifest.xml.
In a previous commit we disabled sending out broadcasts to other apps. This caused some trouble.
For new we hard code 3rd party receiver package names in a resource array. This is supposed to be changed later on, see #824.
> Send out PROVIDER_CHANGED broadcasts again, fixes #822

- opentasks/src/main/res/drawable/ic_opentasks_adaptive_fg.xml
Fixes the adaptive icon being too small by using 108dp instead of the old 24dp, as per this official Android guide: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
Note: according to the guide 108dp is the default for Android >7.1. I do not have access to any devices with version <=7.1 so did not test on those.
Should close #827
> fix adaptive icon being too small

- opentasks-provider/build.gradle
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderObserverTest.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/matchers/NotifiesMatcher.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/matchers/UriMatcher.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskProvider.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/CursorContentValuesInstanceAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/CursorContentValuesListAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/CursorContentValuesTaskAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/ContainsValues.java
- opentasks-provider/src/test/java/org/dmfs/provider/tasks/utils/ContainsValuesTest.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tables/LocalTaskListsTable.java
Updates TaskProvider to skip updates which don't change any value. In such case no database operation is necessary and no notifications will be triggered.
> Don't perform noop updates, implements #836

- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderRecurrenceTest.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/InstanceValuesIterable.java
Recurring tasks may specify a dtstart and due date (instead of a duration). If the task was an all-day task, we may have tried to add a duration derived from the difference between start and due.
The result was a non-all-day duration (although in most cases being a multiple of 24h) and adding this to an all-day date resulted in an error. It's fixed by converting the duration into a proper
all-day duration.
> Fix handling calculation of duration of all-day recurring task, fixes #840

- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/AbstractTaskAdapter.java
Apparently there are tasks which have a recurrence rule but neither a dtstart nor a due date. This caused an NPE. By treating such tasks as non-recurring this should be fixed.
> Ignore recurrence if start and due are absent, fixes #841

- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderRecurrenceTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/TaskInstanceIterable.java
This commit (temporarily) allows tasks with floating start or due and absolute until part in the RRULE and vice versa.
Apparently such tasks exist and we didn't validate this condition. So for now we tolerate this issue until we can be sure
the database won't contain such tasks.
> Tolerate floating time mismatch, fixes #850

- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/DueData.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/TimeData.java
- opentaskspal/src/test/java/org/dmfs/opentaskspal/tasks/DueDataTest.java
- opentaskspal/src/test/java/org/dmfs/opentaskspal/tasks/TimeDataTest.java
`DueData` and `TimeData` should not set recurrence values. That's not allowed on the instances table and, apparently, it's very unexpected and error prone.
> Let Due and Time data not set recurrence values. Fixes #858

- opentasks/src/main/java/org/dmfs/tasks/TaskListFragment.java
- opentasks/src/main/java/org/dmfs/tasks/utils/ExpandableGroupDescriptorAdapter.java
Under certain conditions the CursorTreeAdapter might have had a null Cursor. This commit attempts to fix this by passing an empty MatrixCursor instead. Hopefully this fixes #758 until we got rid of the CursorTreeAdapter.
>  Always pass-non-null group cursor, fixes #758

- dependencies.gradle
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/With.java
- opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java
- opentasks/src/main/java/org/dmfs/tasks/StaleListBroadcastReceiver.java
- opentasks/src/main/java/org/dmfs/tasks/notification/ActionService.java
- opentasks/src/main/java/org/dmfs/tasks/notification/TaskNotificationService.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/predicates/IsProperty.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/predicates/IsRelation.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/predicates/TaskOnList.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/rowsets/Subtasks.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tables/TaskListScoped.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/views/TaskListScoped.java
The Task Editor used to launch the details view for newly created tasks using the task Uri. In general this works, but it fails when the details view uses the Uri with the notification service (because that currently requires an instance Uri). So to fix this we load the first instance after creating a new task and use that one to show the details view.
> Open first instance of newly created task, fixes #862

- dependencies.gradle
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderDetachInstancesTest.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderRecurrenceTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskProvider.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/instances/Detaching.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/instances/TaskValueDelegate.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/AutoCompleting.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Instantiating.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Validating.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/TaskInstanceIterable.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/utils/Timestamps.java
- opentasks-provider/src/test/java/org/dmfs/provider/tasks/utils/TaskInstanceIterableTest.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/RDatesTaskData.java
- opentaskspal/src/main/java/org/dmfs/opentaskstestpal/InstanceTestData.java
- opentaskspal/src/test/java/org/dmfs/opentaskstestpal/InstanceTestDataTest.java
In order to support simple recurrence models and also keep long running tasks small we detach completed instances at the beginning of a series into separate task instances.
> Detach completed instances, #617

- opentasks/src/main/java/org/dmfs/tasks/utils/ExpandableGroupDescriptorAdapter.java
Try to work around the crash caused by an IllegalStateException by always returning a valid group view. Some change in Android seems to cause this. We'll keep this workaround until we've removed the `ExpandableListView`for good.
> Try workaround für #758

- opentasks/src/main/java/org/dmfs/tasks/StaleListBroadcastReceiver.java
Use an important notification to inform the user about a stale list rather than launching an activity from the background.
> Notify about stale lists, fixes #917

- opentasks/src/main/java/org/dmfs/tasks/actions/UpdateWidgetsAction.java
- opentasks/src/main/java/org/dmfs/tasks/homescreen/TaskListWidgetUpdaterService.java
- opentasks/src/main/java/org/dmfs/tasks/notification/ActionService.java
This is an attempt to fix issue #17.
I hope it is not too bad style to talk to the widgets from the notification-related `ActionService`.
> Update widgets when task starts or becomes due

- opentasks-contract/src/main/java/org/dmfs/tasks/contract/TaskContract.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderReparentingTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/TaskProvider.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/model/TaskAdapter.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Reparenting.java
PARENT_ID was meant to serve as a shortcut to parent-child relationships between tasks, for both writing and reading.
While the reading part already works (with the exception of issue #877) the writing part didn't work yet. This is fixed by this commit.
> Update task relationships when updating PARENT_ID, implements #454

- opentasks-contract/src/main/java/org/dmfs/tasks/contract/TaskContract.java
- opentasks-provider/src/androidTest/java/org/dmfs/provider/tasks/TaskProviderRelatingTest.java
- opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Relating.java
When a child task refers to its parent via the parents UID and the parent is inserted after the child, we need to update the PARENT_ID of the child once the parent is available.
> Update PARENT_ID of child task referring via UID, fixes #877

- opentaskspal/src/main/java/org/dmfs/opentaskspal/readdata/EffectiveDueDate.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasklists/ColorData.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasklists/OwnerData.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasklists/SyncStatusData.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasklists/VisibilityData.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/PropertyData.java
- opentaskspal/src/main/java/org/dmfs/opentaskspal/tasks/RelationData.java
- opentaskspal/src/test/java/org/dmfs/opentaskspal/tasklists/ColorDataTest.java
- opentaskspal/src/test/java/org/dmfs/opentaskspal/tasklists/OwnerDataTest.java
- opentaskspal/src/test/java/org/dmfs/opentaskspal/tasklists/SyncStatusDataTest.java
- opentaskspal/src/test/java/org/dmfs/opentaskspal/tasklists/VisibilityDataTest.java
- opentaskspal/src/test/java/org/dmfs/opentaskspal/tasks/PropertyDataTest.java
- opentaskspal/src/test/java/org/dmfs/opentaskspal/tasks/RelationDataTest.java
This adds a few more RowData implementations to support the implementation of SubTasks.
> Add OpenTasksPal classes to support SubTasks, #442

- opentasks-theme/src/main/res/values/attrs.xml
- opentasks-theme/src/main/res/values/theme_dark.xml
- opentasks-theme/src/main/res/values/theme_light.xml
- opentasks/src/main/res/drawable/task_progress_background_shade.xml
Before Android 10, colors in drawables must either all use attr
references or colors, not a mix of both, see https://stackoverflow.com/questions/35363335/gradient-crashes-with-illegalargumentexception-on-android-m
> Fix progress gradient colors, fixes #1019

- opentasks/src/main/java/org/dmfs/tasks/widget/DescriptionFieldView.java
At present it's still unclear under which condition this issue was
triggered. It should no longer crash though, the UI might just behave a
bit strangely instead.
> Fix potential StringIndexOutOfBoundsException, fixes #1020
